### ISSUE TITLE
Cannot use PhpOffice\PhpSpreadsheet\Spreadsheet as Spreadsheet because the name is already in use

### ISSUE THREAD

**Issue by mayunf** [lkq0929/illusion-excel#1]
报错信息：
Cannot use PhpOffice\PhpSpreadsheet\Spreadsheet as Spreadsheet because the name is already in use

代码：

        $importFile = UploadedFile::getInstance($this,'file');
        $rawData  = \Yii::$app->excel->read($importFile->tempName);

compose.json 配置：
"phpoffice/phpspreadsheet": "^1.4",
        "illusion/yii2-excel": "^1.2"

**Comment by lkq0929** [comment]
名字相同，但是命名空间不一样的，你引入的类命名空间是错误的，所以会出现这种错误

**Comment by lkq0929** [comment]
请移步至扩展的例子下，应该是传入的参数有问题
if (\Yii::$app->request->isPost) {
            $importFile = UploadedFile::getInstanceByName('file');
 }
