### ISSUE TITLE
WorkSheet.php更名Worksheet.php

### ISSUE THREAD

**Issue by buyu2272** [lkq0929/illusion-excel#4]
在Spreadsheet.php文件的地52行，此处的Worksheet，在Linux下报错：Class 'illusion\excel\Worksheet' not found，Linux对文件名大写敏感，请求改WorkSheet.php文件名改为Worksheet.php
`$this->worksheet    = new Worksheet($this->_spreadsheet);`

**Comment by lkq0929** [comment]
应该是你环境搭建的问题，更新到最新版本试试v1.2.5 版本,linux 环境下，亲测没问题。
